#!/bin/bash -eu

TITLE="TeslaUSB"
MESSAGE=""
PRIORITY="0"

if [ "$#" -eq 1 ] && [[ "$1" =~ ^[0-9]+$ ]]
then
  TITLE="Dashcam Copy Complete"
  MESSAGE="$1 file(s) were copied."
else
  TITLE="${1:-TeslaUSB}"
  MESSAGE="${2:-}"
  PRIORITY="${3:-0}"
fi

function log () {
  echo "$( date )" >> "$LOG_FILE"
  echo "$1" >> "$LOG_FILE"
}

if [ -z "$MESSAGE" ]
then
  exit 0
fi

if [ -r "/root/.teslaCamPushoverCredentials" ]
then
  log "Sending Pushover message: $TITLE"

  source /root/.teslaCamPushoverCredentials

  curl -F "token=$pushover_app_key" \
  -F "user=$pushover_user_key" \
  -F "title=$TITLE" \
  -F "message=$MESSAGE" \
  -F "priority=$PRIORITY" \
  https://api.pushover.net/1/messages
fi
